development:
  adapter: postgresql
  encoding: unicode
  database: octocats-travels-app_development
  pool: 5
  host: localhost
  username: action
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: octocats-travels-app_test
  pool: 5
  host: localhost
  username: action
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: octocats-travels-app_production
  pool: 5
  host: localhost
  username: action
  password:
